// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpeN028CRiJ-TmoaGKLtQmnuROFlxIaTo',
    appId: '1:739503028370:web:9ad18c6ab3900def060e4b',
    messagingSenderId: '739503028370',
    projectId: 'agro-nepal',
    authDomain: 'agro-nepal.firebaseapp.com',
    storageBucket: 'agro-nepal.appspot.com',
    measurementId: 'G-P3T27ZMXQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcr7gTLyMDthwpaw4qnvLWUTMvTHiDis',
    appId: '1:739503028370:android:6145760ad82d3c3a060e4b',
    messagingSenderId: '739503028370',
    projectId: 'agro-nepal',
    storageBucket: 'agro-nepal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBKfvOaFcInoV6lPpo1NohJWPM8DES2U',
    appId: '1:739503028370:ios:085a916c5b8f1025060e4b',
    messagingSenderId: '739503028370',
    projectId: 'agro-nepal',
    storageBucket: 'agro-nepal.appspot.com',
    iosClientId: '739503028370-96loml5hqllf2r3vmrqgel8i2lbspoet.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroNepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBKfvOaFcInoV6lPpo1NohJWPM8DES2U',
    appId: '1:739503028370:ios:085a916c5b8f1025060e4b',
    messagingSenderId: '739503028370',
    projectId: 'agro-nepal',
    storageBucket: 'agro-nepal.appspot.com',
    iosClientId: '739503028370-96loml5hqllf2r3vmrqgel8i2lbspoet.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroNepal',
  );
}
